services:
  postgres:
    image: postgres:16-alpine
    container_name: kyooar_postgres_local
    environment:
      POSTGRES_DB: kyooar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kyooar_network

volumes:
  postgres_data:

networks:
  kyooar_network:
    driver: bridge