version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: lecritique_postgres
    environment:
      POSTGRES_DB: lecritique
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lecritique_network

  redis:
    image: redis:7-alpine
    container_name: lecritique_redis
    ports:
      - "6379:6379"
    networks:
      - lecritique_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lecritique_api
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=lecritique
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - lecritique_network

volumes:
  postgres_data:

networks:
  lecritique_network:
    driver: bridge
